##################################################
# Generated by GPT 5.1
# Modified by Hakjin Lee, Dept. of Physics, KAIST
##################################################

# pip install reportlab pillow

from reportlab.lib.pagesizes import A4, landscape
from reportlab.pdfgen import canvas
from PIL import Image
from tqdm import tqdm
import os

def img2PdfHorizontal(img_triplets, out_pdf_path, page_size=A4, margin=50):
    """
    ## img2PdfHorizontal
    **: collect three images and put in one page of pdf, horizontally (A4 landscape)**

    ### Input
    - img_triplets : list form of [img_n_1, img_n_2, img_n_3] for each page\\
                    ex: [
                        ["img_1_1.png", "img_1_2.png", "img_1_3.png"],
                        ["img_2_1.png", "img_2_2.png", "img_2_3.png"],
                        ...
                       ]
    - out_pdf_path : path for output pdf (ex: 'output.pdf')
    - page_size    : base page size (default A4, will be turned into landscape)
    - margin       : margin (pt, 1pt ≈ 1/72 inch)
    """
    # page mode : horizontal A4 (landscape)
    page_size_landscape = landscape(page_size)
    page_w, page_h = page_size_landscape

    # generate Canvas
    c = canvas.Canvas(out_pdf_path, pagesize=page_size_landscape)

    slot_width = (page_w - 2 * margin) / 3   # width of a image
    slot_height = page_h - 2 * margin        # heigh of a image

    for triplet in tqdm(img_triplets):
        if len(triplet) != 3:
            raise ValueError("Each page should have 3 images. (img_n_1, img_n_2, img_n_3)")

        for i, img_path in enumerate(triplet):
            # read image size
            with Image.open(img_path) as img:
                img_w, img_h = img.size

            # maximize the size of images, not changing the ratio of image
            scale = min(slot_width / img_w, slot_height / img_h)
            draw_w = img_w * scale
            draw_h = img_h * scale

            # x coord. : align to the center of i-th block (left->right)
            slot_left = margin + i * slot_width
            x = slot_left + (slot_width - draw_w) / 2

            # y coord. : align to the center
            y = (page_h - draw_h) / 2

            c.drawImage(img_path, x, y, width=draw_w, height=draw_h)

        # end of a page
        c.showPage()

    # Save all pdf
    c.save()

if __name__ == "__main__":
    
    base_path = "C:/Users/dlgkr/OneDrive/Desktop/code/astronomy/asteroid_AI/data_analysis/testset_model_analysis_imgs/"
    folder_paths = ["train1122_1/", "train1129_1/", "train1129_2/"]

    # img lists for each folder (sorted)
    img_paths = [sorted(os.listdir(base_path + folder_path)) for folder_path in folder_paths]

    img_triplets = [
        [base_path + folder_paths[0] + img_paths[0][i],
         base_path + folder_paths[1] + img_paths[1][i],
         base_path + folder_paths[2] + img_paths[2][i]]
        for i in range(len(img_paths[0]))
    ]

    img2PdfHorizontal(
        img_triplets[::4],
        base_path + "img2PdfHorizontal_landscape.pdf"
    )
